### PR TITLE
Dev/refactor pullrequest

### PR DESCRIPTION
**Pull request by thijsdezoete**

### CODE REVIEW

**Comment by bnkr** [comment]
The reason I didn't do it this way is that I didn't want to record metrics at all just in case I mess up something I didn't mean to (and to be pedantic it means another 'if' in the send loop).  I probably made this a bit unclear since the ThreadFakeStatsd does create a statsd client anyway...

Maybe there could be a --stdout and a --noop flag to make it more clear, but I'm not sure you would ever use --noop without --stdout...  What do you think?

(edit: or perhaps your intent was just so there wasn't two options for debugging.  In that case you could have --noop which implies --debug and then you don't need to add --stdout ?)

**Comment by thijsdezoete** [comment]
Hey,

Yeah, what I tried to achieve is keep the number of cli options to a minimal. What you're suggesting here is that you wish statsd not to send the actual data, which would influence the program's functionality aka: it no longer working - not something many people would/should use on production imo. Testing however is a whole different story. What we could do is a --dry-run which would imply that your setup wouldn't hurt production. How does that sound?

**Comment by bnkr** [comment]
Yes, that is what I was intending.  I definitely didn't want --debug to turn everything off which is why I used a different option name.

So to confirm: we would have 
- --debug = print metrics on stdout 
- --dry-run (or --noop, whichever you prefer) = don't send metrics to statsd; impies --debug.

Do you want me to revise my patch for this?  If so would you like me to use a FakeStatsd thread or use if-statements in the real statsd.

**Comment by thijsdezoete** [comment]
@bnkr I've updated the pull request here, are you happy with this setup?

**Comment by thijsdezoete** [comment]
I've let the debug mode in, since I can imagine this actually come in handy, but maybe we could just leave it out as well

**Comment by bnkr** [comment]
I'm happy with this.  It does occur now that probably fakestatsd should have a noop 'configure()' as well but I think that can be left.

I expect leaving --debug in is a good idea since you could use it to configure python log level at some point, e.g. print connection details and so on.

Thanks for all the effort.

**Comment by thijsdezoete** [comment]
Yah, we can still override the configure, it would make sense actually. Let me find some other people to think about this as well. :D

**Comment by thijsdezoete** [comment]
Ah, and we forgot to update the readme

**Comment by bnkr** [comment]
I'll do that.

**Comment by thijsdezoete** [comment]
:+1:

**Pull request merged**
